### ISSUE TITLE
still working?

### ISSUE THREAD

**Issue by xinput** [javerous/freshrss-greader-redate#3]
Hello,

is this extension still working, as on my Reeder iOS Client it still shows fetching date on all feeds.

Thanks.

**Comment by javerous** [comment]
@xinput Hi - Apparently yes, I use it on my own FreshRSS instance, and I see the proper dates on my Reeder (macOS & iOS).

Perhaps the feed you are using is not giving publishing date ?

**Comment by xinput** [comment]
hey @javerous , thanks for coming back to me. I've rechecked with a dedicated setup of TTRSS and there it seems that reeder app get's the correct publishing date, so for the moment I migrated away from freshRSS to TTRSS. |

Thank you anyway!

**Comment by Wever1985** [comment]
Sorry for reviving this but I _actually_ think the extension doesn't work properly anymore. (Switching to another RSS reader isn't a solution for me)

I [double](https://user-images.githubusercontent.com/52816917/229283817-b46047be-1f87-4f65-a188-d4455b8c4c2b.png) [checked](https://user-images.githubusercontent.com/52816917/229283824-06277a00-1e8a-4d12-af23-60921a0a13e5.png) that the feeds do provide a publishing date yet Reeder still shows the fetching date instead.
The extension is installed and [enabled.](https://user-images.githubusercontent.com/52816917/229283827-8f116c0d-f2bf-425c-9ba4-b7bf22fc6cad.png)

**Comment by javerous** [comment]
Hi @Wever1985 - I need to check more deeply, because it _looks_ like it still work for me (I still see the propers dates under Reeder).
