### ISSUE TITLE
Bug - blank page 

### ISSUE THREAD

**Issue by oleole39** [javerous/freshrss-greader-redate#4]
Hello,

Using FreshRSS 1.20.2 on Yunohost 11.1.24 (Debian 11), when I enable the extension in the extensions' page, FreshRSS displays a blank page (whatever URL trying to be reached in the FreshRSS instance). 
When I remove the xExtension-GReaderRedate extension's directory, everything goes back to normal.

**Comment by javerous** [comment]
Hi @oleole39 - can you try this version ?
[xExtension-GReaderRedate.tgz](https://github.com/javerous/freshrss-greader-redate/files/12306829/xExtension-GReaderRedate.tgz)

**Comment by oleole39** [comment]
Hello @javerous,
Encountered again the same issue as described initially (now using FreshRSS 1.21.0)  after just unarchiving the file your provided in the extension directory.

**Comment by javerous** [comment]
@oleole39 Okay. I'm not sure what is the issue, then. I'm not reproducing on my own server.

Do you see anything which is not private but still related to the extension in FreshRSS logs that you can share here ?

**Comment by oleole39** [comment]
@javerous Now trying with 1.21.0 and greader-redate 1.2 I've got the same issue. Additional details:
- FreshRSS log in /var/log/freshrss/freshrss.log only includes data related to feeds actualizations.
- Logs at `https://{freshRSShomeURL}/i/?a=logs` do no mention anything about the error (when the extension is in the folder the log page cannot be reached, but after the extension is removed, nothing relates to it in the logs). 
- The console shows a 500 error (Internal Server Error) when trying to perform a GET request to the requested page `https://{freshRSShomeURL}/i/`. There is no such error when greader-redate is removed.
- The error seems to be triggered by the extension.php file (as when renamed in php.old FreshRSS works again) 
  - commenting everything in that file between the php tags makes FreshRSS works
  - commenting everything inside the class of that file leads to the blank page error.
 
Let me know if I can help further.

**Comment by javerous** [comment]
I have no idea what is happening for you. It's perhaps a server configuration issue ?

It works fine for me (and apparently I'm not the only one). Perhaps check your server logs (php / nginx / apache / FIXME) to see why it generate a 500 error ?

**Comment by oleole39** [comment]
Nginx log was the way to go and showed me there was a small typo. 
I created PR #5 for that purpose.
Best,
oleole39

**Comment by javerous** [comment]
Good catch, thanks !
